### ISSUE TITLE
decodeURI

### ISSUE THREAD

**Issue by SoClear** [FranCarstens/docsify-breadcrumb#3]
![image](https://github.com/user-attachments/assets/f0b37412-d679-4e54-b9a5-d868fe429fc2)

**Comment by SoClear** [comment]
I think #4 is the solution.
![image](https://github.com/user-attachments/assets/27073e40-cb91-4a62-8730-8ba1eb99bc17)

**Comment by FranCarstens** [comment]
Thank you for your contribution, @SoClear. This should now be available in [v1.0.4](https://github.com/FranCarstens/docsify-breadcrumb/releases/tag/v1.0.4)
